### ISSUE TITLE
No nodes available

### ISSUE THREAD

**Issue by Tendoglass** [zachchan105/Pricecoin#3]

**Comment by jgalode** [comment]
Hi,

addnode=138.68.30.234:2333
addnode=140.82.33.208:55128
addnode=148.251.182.199:2333
addnode=153.232.10.170:2333
addnode=185.214.69.131:2333
addnode=41.177.145.102:9044
addnode=5.189.142.115:50920
addnode=59.14.193.148:2333
addnode=67.11.180.62:2333
addnode=93.186.255.202:39818
